---
address: "[::]"
port: 5001
services:
  webserver-b:
    ipv6_addresses:
      - fcbb:cc00:2::a
    intents:
      - intent_list: 
          - low-latency
        sid:
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
      - intent_list: 
          - high-latency
        sid:
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
      - intent_list: 
          - flex-algo
          - low-latency
          - low-bandwidth
        sid:
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
  webserver-c:
    ipv6_addresses:
      - fcbb:cc00:3::a
    intents:
      - intent_list: 
          - high-bandwidth
        sid: 
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
      - intent_list: 
          - flex-algo
        sid: 
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
  webserver-d:
    ipv6_addresses:
      - fcbb:cc00:4::a
      - fcbb:cc00:4::b
      - fcbb:cc00:4::c
    intents:
      - intent_list: 
          - flex-algo
          - high-bandwidth
        sid: 
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2
      - intent_list: 
          - high-bandwidth
        sid: 
          - fcbb:bb00:1::2
          - fcbb:bb00:3::2